[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run prisma:generate && npm run prisma:migrate && node server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"